#!/bin/bash
DATE=$(date +"%Y-%m-%d_%H%M")
ZIPFILE="editecho_review_$DATE.zip"

zip -r "$ZIPFILE" \
    $(find . -maxdepth 1 -type f ! -name "*.zip" ! -name ".DS_Store" ! -name "*.iml") \
    libs.profiles \
    app/src/main/java/com/editecho \
    -x "*.git*" "*build*" "*.idea*" "*.gradle*" "*__pycache__*" "*test*" "*tests*" "*.zip"
